[versions]
agp = "8.13.1"
kotlin = "2.1.10"
pandora = "2.1.0"
radarny = "1.0.6"
annotation = "1.9.1"

[libraries]
#组件库
ink-lodz-pandora = { group = "ink.lodz", name = "pandora", version.ref = "pandora" }
ink-lodz-radarny = { group = "ink.lodz", name = "radarny", version.ref = "radarny" }

#注解依赖
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
