[versions]
agp = "8.13.1"
kotlin = "2.1.10"
pandora = "2.1.0"
radarny = "1.0.8"
annotation = "1.9.1"
publish = "0.35.0"

#插件
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

#依赖库
[libraries]

ink-lodz-pandora = { group = "ink.lodz", name = "pandora", version.ref = "pandora" } #组件库
ink-lodz-radarny = { group = "ink.lodz", name = "radarny", version.ref = "radarny" } #雷达图
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" } #注解